/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groups;

/**
 *
 * @author Kiko
 */
import java.awt.CardLayout;
import java.awt.Font;
public class GUI extends javax.swing.JFrame {
    private CardLayout layCard;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        layCard = new CardLayout();
        panCard.setLayout(layCard);
        panCard.add("pan1",pan1);
        panCard.add("pan2",pan2);
        panCard.add("pan3",pan3);
        panCard.add("pan4",pan4);
        choiceBigSmall.add("Bigger Groups");
        choiceBigSmall.add("Smaller Groups");
        Font font = new Font("monospaced", Font.PLAIN, 12);
        result.setFont(font);
        
        
        
    }
    public void goPan(int pan){
        layCard.show(panCard, "pan"+pan);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panCard = new javax.swing.JPanel();
        pan1 = new javax.swing.JPanel();
        names = new java.awt.TextArea();
        namesSubmit = new java.awt.Button();
        pan2 = new javax.swing.JPanel();
        groupSize = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        sessions = new java.awt.TextField();
        numberSubmit = new java.awt.Button();
        pan3 = new javax.swing.JPanel();
        result = new java.awt.TextArea();
        restart = new java.awt.Button();
        pan4 = new javax.swing.JPanel();
        choiceBigSmall = new java.awt.Choice();
        submitChoice = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panCard.setLayout(new java.awt.CardLayout());

        names.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        namesSubmit.setLabel("Submit");
        namesSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(namesSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(names, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(namesSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        namesSubmit.getAccessibleContext().setAccessibleName("Submit");

        panCard.add(pan1, "card2");

        label1.setText("Group Size");

        label2.setText("Sessions to Generate");

        numberSubmit.setLabel("Submit");
        numberSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(525, Short.MAX_VALUE))
        );

        pan2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {groupSize, label2, sessions});

        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(groupSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(numberSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        panCard.add(pan2, "card2");

        result.setEditable(false);

        restart.setLabel("Re-Submit");
        restart.setName(""); // NOI18N
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panCard.add(pan3, "card2");

        submitChoice.setLabel("Submit");
        submitChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan4Layout = new javax.swing.GroupLayout(pan4);
        pan4.setLayout(pan4Layout);
        pan4Layout.setHorizontalGroup(
            pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceBigSmall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(664, Short.MAX_VALUE))
        );

        pan4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {choiceBigSmall, submitChoice});

        pan4Layout.setVerticalGroup(
            pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(choiceBigSmall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(submitChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        panCard.add(pan4, "card2");

        getContentPane().add(panCard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namesSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesSubmitActionPerformed
        commandSubmitted=names.getText();
        submitted=true;
    }//GEN-LAST:event_namesSubmitActionPerformed

    private void numberSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSubmitActionPerformed
        // TODO add your handling code here:
        try{
            Integer.parseInt(groupSize.getText());
            Integer.parseInt(sessions.getText());
        }catch(Exception e){
            return;
        }
        commandSubmitted=groupSize.getText()+"\t"+sessions.getText();
        submitted=true;
    }//GEN-LAST:event_numberSubmitActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        commandSubmitted="r";
        submitted=true;
    }//GEN-LAST:event_restartActionPerformed

    private void submitChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitChoiceActionPerformed
       try{
           if(choiceBigSmall.getSelectedIndex() < 0){
               return;
           }
       }catch(Exception e){
           return;
       }
        commandSubmitted=""+choiceBigSmall.getSelectedIndex();
        submitted=true;
    }//GEN-LAST:event_submitChoiceActionPerformed

    public String userInput() throws InterruptedException {
		while (!submitted) {
			Thread.sleep(100);
		}
		submitted = false;
		return commandSubmitted;

	}
    public void setText(String text){
    	result.setText(text);
    }
    /**
     * @param args the command line arguments
     */
private static boolean submitted=false;    
private static String commandSubmitted;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choiceBigSmall;
    private java.awt.TextField groupSize;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextArea names;
    private java.awt.Button namesSubmit;
    private java.awt.Button numberSubmit;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    private javax.swing.JPanel panCard;
    private java.awt.Button restart;
    private java.awt.TextArea result;
    private java.awt.TextField sessions;
    private java.awt.Button submitChoice;
    // End of variables declaration//GEN-END:variables
}
